name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build web app
        run: npm run build

      - name: Set Git user
        run: |
          git config --global user.email "pedromunhozsouza@gmail.com"
          git config --global user.name "PedroMunhozz"

      - name: Create known_hosts file
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts

      - name: Deploy to gh-pages
        env:
          GH_TOKEN: ${{ secrets.TUDO }}
        run: |
          git checkout -b gh-pages
          git add -f build
          git commit -m "Deploy to GitHub Pages"
          git remote set-url origin git@github.com:PedroMunhozz/TxaTxa.git
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "${GH_TOKEN}" | ssh-add -
          git push -f origin gh-pages
          git checkout -f main
