name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build web app
        run: npm run build

      - name: Deploy to gh-pages
        run: |
          git checkout -b gh-pages
          git add -f build
          git commit -m "Deploy to GitHub Pages"
          git subtree split --prefix build -b gh-pages-temp
          git push -f origin gh-pages-temp:gh-pages
          git branch -D gh-pages-temp
          git checkout -f main
