name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build web-app
        run: |
          npm install
          npm run build
      - name: Deploy to gh-pages
        env:
          PERSONAL_TOKEN: ${{ secrets.TUDO }}
        run: |
          git config --global user.name "PedroMunhozz"
          git config --global user.email "pedromunhozsouza@gmail.com"
          npm run deploy
